### PR TITLE
Refactor/pref modal

### PR DESCRIPTION
**Pull request by tomchentw**
## Depends on

~#26~

## Description

* Migrate PrefModal to bootstrap modal

## Screenshots

screen shot 2017-12-24 at 5 34 09 pm
screen shot 2017-12-24 at 5 34 06 pm

### CODE REVIEW

**Comment by tomchentw** [comment]
@robertabcd please review & merge, thanks!

**Comment by robertabcd** [comment]
Can you separate e531f31a5042b0bc59fbc47996cda94834af9e48 into a new PR? I need more time to look at this PR but I'd like the fix to be cherry-picked.

**Comment by tomchentw** [comment]
Done.

**Comment by robertabcd** [comment]
LGTM. Thanks

**Pull request merged**
