### PR TITLE
Refine input helper

### PR DESCRIPTION
**Pull request by robertabcd**
@tomchentw Can you help me to look at this? I tried to investigate the conflicting event handler issue. I can not trigger the bug with those hacks removed. Do you have instructions to trigger that bug? (I did other small tweaks but I think it's unrelated to the bug.)

### CODE REVIEW

**Review by tomchentw — CHANGES_REQUESTED** [review]
Looks good in general. Just the dragging didn't work properly: 
y04iljuovk


> Do you have instructions to trigger that bug? 

As far as I can recall, it happens when I try to hook event handlers using props and failed to receive callbacks in React. With the help of the debugger, I realized it's related to event handlers defined on the window/document object, which leads me to the hack.

I've run your code on my local and it seems working fine and I guess this is somehow fixed?

**Comment by robertabcd** [comment]
I did notice that happens when the mouse moves too fast and next event happens outside of the dialog. I don't yet have a better solution. movement{X,Y} didn't yield better result to me; it slightly lose track when moved slowly.

**Review by tomchentw — APPROVED** [review]
Got it. Let's just do it and see how it goes.

**Comment by robertabcd** [comment]
Or were you trying to mention other issues? I can't quite get that from the gif.

**Comment by tomchentw** [comment]
Nope. Exactly what you're talking about.

**Comment by robertabcd** [comment]
Uh, okay. Thanks

**Comment by tomchentw** [comment]
Please delete the branch after merged, thanks!

**Pull request merged**
